query GetHomes {
  homeCollection {
    items {
      sys {
        id
      }
      name
      city
      state
      photo {
        url
      }
    }
  }
}

query GetHomeDetail($id: String!) {
  home(id: $id) {
    name
    city
    state
    laundry
    availableUnits
    wifi
    photo {
      url
    }
  }
}
