export const housingLocations = [
  {
    id: 0,
    name: 'Acme Fresh Start Housing',
    city: 'Chicago',
    state: 'IL',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/31sfgeneralbrowncraftsmanZH2J.png`,
    availableUnits: 4,
    wifi: true,
    laundry: true,
  },
  {
    id: 1,
    name: 'A113 Transitional Housing',
    city: 'Santa Monica',
    state: 'CA',
    photo: `https://www.swsol.org/sites/default/files/styles/call_to_action/public/2023-01/SWS%20Home.jpeg?h=0e58d73d&itok=oEb95mpC`,
    availableUnits: 0,
    wifi: false,
    laundry: true,
  },
  {
    id: 2,
    name: 'Warm Beds Housing Support',
    city: 'Juneau',
    state: 'AK',
    photo: `https://www.fau.edu/newsdesk/images/news/april-housing-pic.jpg`,
    availableUnits: 1,
    wifi: false,
    laundry: false,
  },
  {
    id: 3,
    name: 'Homesteady Housing',
    city: 'Chicago',
    state: 'IL',
    photo: `https://www.bankrate.com/2023/02/08153710/overvalued-housing-markets.jpg?auto=webp&optimize=high&crop=16:9&width=912`,
    availableUnits: 1,
    wifi: true,
    laundry: false,
  },
  {
    id: 4,
    name: 'Happy Homes Group',
    city: 'Gary',
    state: 'IN',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/04house1970sIO5M.png`,
    availableUnits: 1,
    wifi: true,
    laundry: false,
  },
  {
    id: 5,
    name: 'Hopeful Apartment Group',
    city: 'Oakland',
    state: 'CA',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/07construction1970s4YAX.png`,
    availableUnits: 2,
    wifi: true,
    laundry: true,
  },
  {
    id: 6,
    name: 'Seriously Safe Towns',
    city: 'Oakland',
    state: 'CA',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/03splitlevelhouse1973KY1B.png`,
    availableUnits: 5,
    wifi: true,
    laundry: true,
  },
  {
    id: 7,
    name: 'Hopeful Housing Solutions',
    city: 'Oakland',
    state: 'CA',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/11interestrates1980D0RU.png`,
    availableUnits: 2,
    wifi: true,
    laundry: true,
  },
  {
    id: 8,
    name: 'Seriously Safe Towns',
    city: 'Oakland',
    state: 'CA',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/00sf26AK88.png`,
    availableUnits: 10,
    wifi: false,
    laundry: false,
  },
  {
    id: 9,
    name: 'Capital Safe Towns',
    city: 'Portland',
    state: 'OR',
    photo: `https://static.stacker.com/s3fs-public/styles/slide_desktop/s3/16Assistedliving0Y6O.png`,
    availableUnits: 6,
    wifi: true,
    laundry: true,
  },
]
